name: fronted
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  file_picker: ^9.2.1
  flutter:
    sdk: flutter
  http: ^1.3.0
  open_file: ^3.5.10
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  flutter_plugin_android_lifecycle: ^2.0.0 
  flutter_markdown: ^0.6.8
  intl: ^0.20.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
